# Generated by Django 4.1.4 on 2023-02-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_vacancy_speciality_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
